-- CASE
-- IF
-- LOOP (WITH EXIT)
-- YOU CAN NAME THE LOOP, IF ETC
-- FOR I IN REVERSE
-- EXERCISES
-- CREATE A PROGRAM THAT WILL ASK THE USER FOR A NUMBER AND THEN PRINT OUT A LIST OF NUMBER FROM 1 TO THE NUMBER
-- ENTERED AND THE SQUARE OF THE NUMBER. FOR EXAMPLE, IF THE USER ENTERED '3' THEN THE PROGRAM WOULD OUTPUT: (1 SQUARED
-- 1. / 2 SQUARED IS 4. / 3 SQUARED IS 9. )

  
ACCEPT USERVALUE PROMPT 'enter number: ';
DECLARE
    USERVAR NUMBER := 1;
BEGIN    
    FOR i IN 1..&USERVALUE LOOP
        DBMS_OUTPUT.put_line('ITERACION: ' || POWER(i,2));
  END LOOP;
END;