-- CASE
-- IF
-- LOOP (WITH EXIT)
-- YOU CAN NAME THE LOOP, IF ETC
-- FOR I IN REVERSE
-- EXERCISES
-- 1. CREATE A PROGRAM THAT WILL ASK THE USER FOR A NUMBER AND THEN PRINT OUT A LIST OF NUMBER FROM 1 TO THE NUMBER
-- ENTERED AND THE SQUARE OF THE NUMBER. FOR EXAMPLE, IF THE USER ENTERED '3' THEN THE PROGRAM WOULD OUTPUT: (1 SQUARED
-- 1. / 2 SQUARED IS 4. / 3 SQUARED IS 9. )

-- 2. 

-- 3. FIND THE DIFFERENCE BETWEEN THE SQUARE OF THE SUM AND THE SUM OF THE SQUARES OF THE FIRST N NATURAL NUMBERS
-- THE SQUARE OF THE SUM OF THE FIRST TEN NATURA NUMBERS IS (1 + 2 + ... + 10)° = 55° = 3025.
-- THE SUM OF THE SQUARES OF THE FIRST TEN NATURAL NUMBERS IS 1° + 2° + ... + 10° = 385.
-- HENCE THE DIFFERENCE BETWEEN THE SQUARE OF THE SUM OF THE FIST TEN NATURAL NUMBERS AND THE SUM OF THE SQUARES OF 
-- THE FIRST TEN NATURAL  NUMBERS IS 3025 - 385 = 2640.

  
ACCEPT USERVALUE PROMPT 'enter number: ';
DECLARE
    USERVAR NUMBER := 1;
BEGIN    
    FOR i IN 1..&USERVALUE LOOP
        DBMS_OUTPUT.put_line('ITERACION: ' || POWER(i,2));
  END LOOP;
END;

ACCEPT USERVALUE PROMPT 'enter number: ';
DECLARE
    USERVAR NUMBER := 1;
BEGIN    
    FOR i IN 1..&USERVALUE LOOP
        DBMS_OUTPUT.put_line('ITERACION: ' || POWER(i,2));
  END LOOP;
END;